version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./database:/docker-entrypoint-initdb.d  # 挂载初始数据文件夹
      - mongo_data:/data/db

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/cargo_with_tonnage

volumes:
  mongo_data: